version: '3.1'

services:

  db:
    image: postgres
    environment: 
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example_db
    ports:
      - 25432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
